name: Run Gradle on push
on:
  push:
    branches:
      - main
jobs:
  gradle:
    strategy:
      matrix:
        os: [windows-latest] # since we will run the final product on windows, we will use windows to build it
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 1.8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: altf4.jar
          path: build/libs/altf4-1.0-SNAPSHOT-all.jar