name: Run Gradle on push
on:
  push:
    branches:
      - main
jobs:
  gradle:
    strategy:
      matrix:
        os: [windows-latest] # since we will run the final product on windows, we will use windows to build it
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ env.GITHUB_RUN_NUMBER }}"
          files: |
            build/libs/altf4-1.0-SNAPSHOT-all.jar